var __dmapValues = {"mappings":{"address":"address", "loanamount":"amount_of_loan", "duedate":"baby_due_date", "disabilityhaslawyer":"disability_haslawyer", "disabilityoutofwork":"disability_outofwork", "disabilityseendoctor":"disability_seendoctor", "disabilitystillworking":"disability_still_working", "phonecellconsent":"phone_consent", "twitterhandle":"twitter", "twitterusername":"twitter", "twitteruser":"twitter", "addressfromid":"\ufeffaddress_from_id", "addressscore":"address_score", "addressvalidated":"address_validated", 
"address1":"address1", "address2":"address_2", "afbage":"afb_age", "affinity":"affinity", "agentid":"agent_id", "amountofloan":"amount_of_loan", "appraisedhomevalue":"appraised_home_value", "areaofstudy":"area_of_study", "babyduedate":"baby_due_date", "backpain":"back_pain", "bankruptcy":"bankruptcy", "bankruptcydate":"bankruptcy_date", "benefitwithdirdeposit":"benefit_with_dir_deposit", "besttime":"best_time", "bizop":"bizop", "boss":"boss", "browser":"browser", "buyer":"buyer", "carleaseown":"car_lease_own", 
"carmake":"car_make", "carmodel":"car_model", "carowner":"car_owner", "carwarrantyintent":"car_warranty_intent", "caryear":"car_year", "cashoutrequest":"cash_out_request", "celebrityaspresident":"celebrity_as_president", "celebrityforpresident":"celebrity_for_president", "cellphonevalid":"cellphone_valid", "children":"children", "childrenagegroup":"children_age_group", "childrendob":"children_dob", "chronicpain":"chronic_pain", "cigaretteaffinity":"cigarette_affinity", "cigarettealternate":"cigarette_alternate", 
"cigarettebrand":"cigarette_brand", "cigaretteflavor":"cigarette_flavor", "cigarettepacking":"cigarette_packing", "cigaretteprevious":"cigarette_previous", "cigarettepurchasemethod":"cigarette_purchase_method", "cigarsbrand":"cigars_brand", "cigarsusage":"cigars_usage", "city":"city", "collegecredits":"college_credits", "company":"company", "companyaddress1":"companyaddress1", "companyaddress2":"companyaddress2", "companyannualrevenue":"companyannual_revenue", "companycity":"companycity", "companycountry":"companycountry", 
"companydescription":"companydescription", "companyemail":"companyemail", "companyfax":"companyfax", "companyindustry":"companyindustry", "companyname":"companyname", "companynumberofemployees":"companynumber_of_employees", "companyphone":"companyphone", "companystate":"companystate", "companywebsite":"companywebsite", "companyzipcode":"companyzipcode", "computeraccess":"computer_access", "concernwithmuslim":"concern_with_muslim", "consentdate":"consent_date", "consentforalerts":"consent_for_alerts", 
"consenttime":"consent_time", "country":"country", "county":"county", "coupon":"coupon", "creditscore":"credit_score", "crickettoken":"cricket_token", "currentinterestrate":"current_interest_rate", "currentva":"current_va", "datestartclasses":"date_start_classes", "debtconsolidation":"debt_consolidation", "degreeeducation":"degree_education", "degreelevel":"degree_level", "deliveredmeds":"delivered_meds", "devicecategory":"device_category", "diabetes":"diabetes", "diabeticsupplies":"diabetic_supplies", 
"dipbrand":"dip_brand", "dipusage":"dip_usage", "disability":"disability", "discountaarp":"discount_aarp", "dob":"dob", "dobday":"dob_day", "dobmonth":"dob_month", "dobyear":"dob_year", "donaldtrumpfame":"donald_trump_fame", "downpayment":"down_payment", "ecigarettebrand":"ecigarette_brand", "ecigaretteusage":"ecigarette_usage", "educationlevel":"education_level", "effectiveattackonisis":"effective_attack_on_isis", "eighteenorover":"eighteen_or_over", "email":"email", "emailconsent":"email_consent", 
"emailjobalert":"email_job_alert", "emailreason":"email_reason", "emailscore":"email_score", "emailvalid":"email_valid", "employed":"employed", "employedlast510":"employed_last5_10", "endorsementseffect":"endorsements_effect", "ethnicitygroup":"ethnicity_group", "expforeignpolicy":"exp_foreign_policy", "explicitsurveyinterestkma":"explicitsurveyinterestkma", "facebook":"facebook", "fax":"fax", "fhaloan":"fha_loan", "firsttimehomeowner":"first_time_homeowner", "firsttimeparent":"first_time_parent", 
"firstname":"first_name", "foreclosure":"foreclosure", "formid":"form_id", "formname":"form_name", "foundhome":"found_home", "fourleafactivityscore":"fourleaf_activity_score", "fourleafalgo":"fourleaf_algo", "fourleafhygienereason":"fourleaf_hygiene_reason", "fourleafhygienescore":"fourleaf_hygiene_score", "fourleaflowintel":"fourleaf_low_intel", "foursquare":"foursquare", "gender":"gender", "googleplus":"googleplus", "haveallergies":"have_allergies", "havecarinsurance":"have_car_insurance", "havecheckingaccount":"have_checking_account", 
"havehealthinsurance":"have_health_insurance", "havelifeinsurance":"have_life_insurance", "havemedicaid":"have_medicaid", "haverealtor":"have_realtor", "hazardousoccupation":"hazardous_occupation", "healthinsspecialist":"health_ins_specialist", "healthinsulinuser":"health_insulin_user", "healthprovider":"health_provider", "heightft":"heightft", "heightin":"heightin", "highpayingjobseeker":"high_paying_jobseeker", "homebuyergrants":"home_buyer_grants", "homerentown":"home_rent_own", "homesize":"home_size", 
"homevalue":"home_value", "homeloantype":"homeloan_type", "homeowner":"homeowner", "homephonevalid":"homephone_valid", "householddriver":"household_driver", "householdincome":"household_income", "householdsize":"household_size", "hsgraduationyear":"hs_graduation_year", "impliedhhi":"impliedhhi", "indebt":"in_debt", "indebtamount":"in_debt_amount", "inscoverageamt":"ins_coverage_amt", "instagram":"instagram", "insuranceplantype":"insurance_plan_type", "insurancepredenied":"insurance_pre_denied", "insuranceprovider":"insurance_provider", 
"insurancetype":"insurance_type", "intlifeinsurance":"int_life_insurance", "interestadt":"interest_adt", "interestgetpaidtoreview":"interest_getpaidtoreview", "interestmysteryshopper":"interest_mystery_shopper", "interestrentownhomes":"interest_rent_own_homes", "interestsmsjobalert":"interest_sms_jobalert", "interestsolar":"interest_solar", "interestziprecuriter":"interest_ziprecuriter", "interestedadhd":"interested_adhd", "interestedcleaningsampl":"interested_cleaning_sampl", "interestedcreditscore":"interested_credit_score", 
"interesteddishnetwork":"interested_dish_network", "interestededufield":"interested_edu_field", "interestededucation":"interested_education", "interestedfreebies":"interested_freebies", "interestedlifeinsurance":"interested_life_insurance", "interestedmagazines":"interested_magazines", "interestedmedicaid":"interested_medicaid", "interestedmedicare":"interested_medicare", "interestedstorecoupons":"interested_store_coupons", "interestedsurveys":"interested_surveys", "interesteduberdriving":"interested_uber_driving", 
"ipproxy":"ip_proxy", "job":"job", "jobcategory":"job_category", "jobcompany":"job_company", "jointpains":"joint_pains", "jornayaleadid":"jornayaleadid", "kanyeforpresident":"kanye_for_president", "kimdavisreleasemistake":"kimdavis_release_mistake", "kimdavisrightworng":"kimdavis_right_worng", "lastname":"last_name", "lenderclient":"lender_client", "lenderemail":"lender_email", "licensecourse":"license_course", "licensefromotherstates":"license_from_other_states", "lifealertsystem":"life_alert_system", 
"lifelineprogram":"lifeline_program", "linetype":"line_type", "linkedin":"linkedin", "lyftgeo":"lyftgeo", "magtitle":"mag_title", "magtitle2":"mag_title2", "magtitle3":"mag_title3", "marijuanaagerange":"marijuana_age_range", "marijuanaforrecreation":"marijuana_for_recreation", "marijuanagatewaydrug":"marijuana_gateway_drug", "marijuanalessproductive":"marijuana_less_productive", "marijuanamedicinaluse":"marijuana_medicinal_use", "marijuanaworsealcohol":"marijuana_worse_alcohol", "maritalstatus":"marital_status", 
"medicalcondition":"medical_condition", "medicaretype":"medicare_type", "methodofcontact":"method_of_contact", "middlename":"middle_name", "military":"military", "militarybranch":"military_branch", "militarypaygrade":"military_paygrade", "militaryrelationship":"military_relationship", "militaryrelativeoversea":"military_relative_oversea", "militarystatus":"military_status", "mmn":"mmn", "mobile":"mobile", "monthslate":"months_late", "monthsuntilstart":"months_until_start", "morepay":"more_pay", "mortgagaeinterestrate":"mortgagae_interest_rate", 
"mortgageamount":"mortgage_amount", "mortgagefixedarm":"mortgage_fixedarm", "mortgagegoal":"mortgage_goal", "moving":"moving", "muslimforpresident":"muslim_for_president", "needaditionalcash":"need_aditional_cash", "numcars":"num_cars", "numviewdailyjobs":"num_view_dailyjobs", "numviewhomedaily":"num_view_homedaily", "numviewlenderdaily":"num_view_lenderdaily", "numberschoolsviewdaily":"number_schools_view_daily", "onlineorcampus":"online_or_campus", "operatingsystem":"operating_system", "paindailybasis":"pain_daily_basis", 
"painlocation":"pain_location", "pains":"pains", "petowner":"pet_owner", "phone":"phone", "phonecellcarrier":"phone_cell_carrier", "phonecompanyconsent":"phone_company_consent", "phoneconsent":"phone_consent", "phonehome":"phone_home", "phonehomeconsent":"phone_home_consent", "phonescore":"phone_score", "physicianfirstname":"physician_first_name", "physicianlastname":"physician_last_name", "points":"points", "politicalaffiliation":"political_affiliation", "position":"position", "preferredphone":"preferred_phone", 
"pregnant":"pregnant", "previousaddress1":"previous_address1", "previousaddress2":"previous_address2", "previouscity":"previous_city", "previousstate":"previous_state", "previouszip":"previous_zip", "prison":"prison", "projecttype":"projecttype", "propertydescription":"property_description", "propertypurpose":"property_purpose", "psoriasis":"psoriasis", "ptpareacode":"ptp_area_code", "ptplinenumber":"ptp_line_number", "ptpprefix":"ptp_prefix", "publishersclearinghouse":"publishers_clearing_house", 
"randomvalue":"random_value", "realitytvcandidate":"reality_tv_candidate", "reasonunemployment":"reason_unemployment", "receivingdisbenefits":"receiving_dis_benefits", "receivinggovsubaid":"receiving_gov_sub_aid", "recentlifeevent":"recent_life_event", "recentlifeeventdate":"recent_life_event_date", "referringhost":"referring_host", "referringurl":"referring_url", "refinancemortgagetarget":"refinance_mortgage_target", "relationshiptochild":"relationship_to_child", "religionbeforelaw":"religion_before_law", 
"religionbeliefseffects":"religion_beliefs_effects", "religioneffectonvotes":"religion_effect_on_votes", "religiousperson":"religious_person", "residencylength":"residency_length", "retired":"retired", "reversemortgagetarget":"reverse_mortgage_target", "rnlicense":"rn_license", "russiafightisisinstead":"russia_fight_isis_instead", "salutation":"salutation", "samereligion":"same_religion", "schoolnamematched":"school_name_matched", "schooltype":"school_type", "servicecategory":"service_category", 
"shortpaydayloan":"short_payday_loan", "skype":"skype", "smokelessbrand":"smokeless_brand", "smokelessusage":"smokeless_usage", "smoker":"smoker", "smsconsent":"sms_consent", "spouseage":"spouse_age", "spousedob":"spouse_dob", "spousedobday":"spouse_dob_day", "spousedobmonth":"spouse_dob_month", "spousedobyear":"spouse_dob_year", "spousegender":"spouse_gender", "spouseheightft":"spouse_height_ft", "spouseheightin":"spouse_height_in", "spousesmoker":"spouse_smoker", "spouseweightlbs":"spouse_weight_lbs", 
"ssnlast4":"ssn_last_4", "state":"state", "suffix":"suffix", "supportsamesexmarriage":"support_same_sex_marriage", "switchtodish":"switch_to_dish", "systemdevice":"system_device", "taxdebtid":"tax_debt_id", "taxissuesid":"tax_issues_id", "taxingmarijuana":"taxing_marijuana", "threehourstoenroll":"three_hours_to_enroll", "timeinaddress":"time_in_address", "timezone":"time_zone", "timeframemortgage":"timeframe_mortgage", "timezone1":"timezone1", "title":"title", "tobaccouse":"tobacco_use", "toughestantiterrorism":"toughest_anti_terrorism", 
"treatdrugproblem":"treat_drug_problem", "trustedform":"trusted_form", "twitter":"twitter", "typeofloan":"type_of_loan", "urlconsent":"url_consent", "uscitizen":"us_citizen", "usaforeignconflict":"usa_foreign_conflict", "useofloan":"use_of_loan", "useragent":"user_agent", "uspstype":"usps_type", "utmadgroup":"utm_adgroup", "utmterm":"utm_term", "valoan":"va_loan", "version":"version", "weightlbs":"weight_lbs", "wicstatus":"wic_status", "workphonevalid":"workphone_valid", "xxtrustedformcerturl":"xx_trusted_form_cert_url", 
"zeetoid":"zeeto_id", "zipvalidated":"zip_validated", "zipcode":"zip_code", "ziprecruiterloc":"ziprecruiter_loc", "phonehash":"phone_hash", "id":"id", "eventid":"event_id", "locationid":"location_id", "individualid":"individual_id", "emailid":"email_id", "age":"age", "scoringpartner":"scoring_partner", "scoringdateid":"scoring_date_id", "scorekey":"score_key", "scorevalue":"score_value", "uniqid":"uniq_id", "key":"key", "value":"value", "bankruptcydateid":"bankruptcy_date_id", "creditscoreself":"credit_score_self", 
"campaignname":"campaign_name", "division":"division", "platform":"platform", "vertical":"vertical", "foreigncampaignid":"foreign_campaign_id", "engagecampaignid":"engage_campaign_id", "system":"system", "clientname":"client_name", "clientfamilyid":"client_family_id", "clientagencyofrecord":"client_agency_of_record", "interestdateid":"interest_date_id", "interestkey":"interest_key", "interestvalue":"interest_value", "dispositiontype":"disposition_type", "type":"type", "dispositionchannel":"disposition_channel", 
"sourcename":"source_name", "sourceforeignsystemid":"source_foreign_system_id", "utmsource":"utm_source", "channel":"channel", "ipaddress":"ip_address", "manufacturer":"manufacturer", "devicemodel":"device_model", "agegroup":"agegroup", "dobdateid":"dob_date_id", "incomerange":"income_range", "firstseendateid":"firstseen_date_id", "martialstatus":"martial_status", "datetable":"date_table", "datedimension":"date_dimension", "usholiday":"us_holiday", "caholiday":"ca_holiday", "iaholiday":"ia_holiday", 
"calendaryear":"calendar_year", "calendarquarter":"calendar_quarter", "calendarmonth":"calendar_month", "dayinmonth":"day_in_month", "dayinquarter":"day_in_quarter", "dayinyear":"day_in_year", "dayofweek":"day_of_week", "numberofdaysinmonth":"number_of_days_in_month", "monthinqtr":"month_in_qtr", "monthname":"month_name", "weekinyear":"week_in_year", "interestratetwo":"interest_rate_two", "mortgagetwo":"mortgage_two", "utctimetable":"utc_time_table", "timedimension":"time_dimension", "hour":"hour", 
"minute":"minute", "second":"second", "interesteducation":"interest_education", "esp":"esp", "tcpaconsent":"tcpa_consent", "consenttimedateid":"consent_time_date_id", "consenttimetimeid":"consent_time_time_id", "useragentstring":"user_agent_string", "foreignsystemid":"foreign_system_id", "callrecordinglocation":"call_recording_location", "trustedformcreatedatdateid":"trusted_form_created_at_date_id", "trustedformcreatedattimeid":"trusted_form_created_at_time_id", "trustedformexpiresatdateid":"trusted_form_expires_at_date_id", 
"trustedformexpiresattimeid":"trusted_form_expires_at_time_id", "trustedformshareurl":"trusted_form_share_url", "alcazarlec":"alcazar_lec", "alcazarspid":"alcazar_spid", "alcazarlinetype":"alcazar_linetype", "alcazarocn":"alcazar_ocn", "alcazarlata":"alcazar_lata", "employmentstatus":"employment_status", "eventtype":"event_type", "carmileage":"car_mileage", "carinsuranceprovider":"car_insurance_provider", "transactiondatetimedateid":"transaction_datetime_date_id", "transactiondatetimetimeid":"transaction_datetime_time_id", 
"revenue":"revenue", "cost":"cost", "subid":"sub_id", "term":"term", "engageledgerid":"engage_ledger_id", "addressvalid":"address_valid", "addresslastvalidationdateid":"address_last_validation_date_id", "disposition":"disposition", "dispositiondescription":"disposition_description", "dispositiontypeid":"disposition_type_id", "dispositiontimeid":"disposition_time_id", "dispositiondateid":"disposition_date_id", "dateid":"date_id", "apiuser":"api-user", "mediachannel":"media_channel", "volume":"volume", 
"grosscpl":"gross_cpl", "netcpl":"net_cpl", "prospectrep":"prospect_rep", "salesrep":"sales_rep", "dateadded":"date_added", "contactid":"contact_id", "campaignid":"campaign_id", "bundlename":"bundle_name", "classname":"class_name", "objectid":"object_id", "activity":"activity", "memo":"memo", "contactclientid":"contactclient_id", "attribution":"attribution", "categoryid":"category_id", "createdby":"created_by", "createdbyuser":"created_by_user", "datemodified":"date_modified", "modifiedby":"modified_by", 
"modifiedbyuser":"modified_by_user", "checkedout":"checked_out", "checkedoutby":"checked_out_by", "checkedoutbyuser":"checked_out_by_user", "name":"name", "description":"description", "publishup":"publish_up", "publishdown":"publish_down", "provider":"provider", "accountid":"account_id", "clientid":"client_id", "clientsecret":"client_secret", "token":"token", "campaignsettings":"campaign_settings", "refreshtoken":"refresh_token", "mediaaccountid":"media_account_id", "provideraccountid":"provider_account_id", 
"provideraccountname":"provider_account_name", "providercampaignid":"provider_campaign_id", "providercampaignname":"provider_campaign_name", "provideradsetid":"provider_adset_id", "provideradsetname":"provider_adset_name", "provideradid":"provider_ad_id", "provideradname":"provider_ad_name", "currency":"currency", "spend":"spend", "cpc":"cpc", "cpm":"cpm", "ctr":"ctr", "impressions":"impressions", "clicks":"clicks", "netfirst":"net_first", "netlast":"net_last", "network":"network", "geonameid":"geoname_id", 
"registeredcountrygeonameid":"registered_country_geoname_id", "representedcountrygeonameid":"represented_country_geoname_id", "postalcode":"postal_code", "latitude":"latitude", "longitude":"longitude", "accuracyradius":"accuracy_radius", "localecode":"locale_code", "continentcode":"continent_code", "continentname":"continent_name", "countryisocode":"country_iso_code", "countryname":"country_name", "subdivision1isocode":"subdivision_1_iso_code", "subdivision1name":"subdivision_1_name", "subdivision2isocode":"subdivision_2_iso_code", 
"subdivision2name":"subdivision_2_name", "cityname":"city_name", "metrocode":"metro_code", "referralid":"referral_id", "programid":"program_id", "campusid":"campus_id", "schoolid":"school_id", "sourceid":"source_id", "createdat":"created_at", "status":"status", "marketplaceid":"marketplace_id", "schoolrejectreasonid":"school_reject_reason_id", "rejectreasonid":"reject_reason_id", "url":"url", "site":"site", "producerid":"producer_id", "studyareaid":"study_area_id", "degreelevelid":"degree_level_id", 
"brokerid":"broker_id", "affiliateevent":"affiliate_event", "assisted":"assisted", "campaigncode":"campaign_code", "discounted":"discounted", "test":"test", "buyerid":"buyer_id", "budgetid":"budget_id", "contactme":"contact_me", "searchid":"search_id", "consentid":"consent_id", "budgetlimitid":"budget_limit_id", "realtimeaccepted":"real_time_accepted", "message":"message", "postdata":"post_data", "manual":"manual", "referrals":"referrals", "companyid":"company_id", "targetid":"target_id", "providersubid":"provider_sub_id", 
"providertransid":"provider_trans_id", "usersessionid":"user_session_id", "returnurl":"return_url", "landingurl":"landing_url", "optedout":"opted_out", "updatesent":"update_sent", "searchterms":"search_terms", "campaign":"campaign", "adgroup":"ad_group", "ad":"ad", "keyword":"keyword", "pageviewscount":"page_views_count", "elapsedtime":"elapsed_time", "hybrid":"hybrid", "articleviewscount":"article_views_count", "educationlevelid":"education_level_id", "agelevel":"age_level", "hsgradyear":"hs_grad_year", 
"militaryaffiliation":"military_affiliation", "recircid":"recirc_id", "originalid":"original_id", "agent":"agent", "tags":"tags", "timetocall":"time_to_call", "layout":"layout", "creative":"creative", "degreelevelgroupid":"degree_level_group_id", "initialproviderid":"initial_provider_id", "creativeurl":"creative_url", "contacts":"contacts", "zip":"zip", "phone1":"phone_1", "phone2":"phone_2", "phone3":"phone3", "phone1type":"phone1_type", "phone2type":"phone2_type", "phone3type":"phone3_type", "prefix":"prefix", 
"daylightsavings":"daylight_savings", "addresstype":"address_type", "autozip":"auto_zip", "autocity":"auto_city", "autostate":"auto_state", "searches":"searches", "providerid":"provider_id", "degreelevelids":"degree_level_ids", "studyareaids":"study_area_ids", "submittedschoolids":"submitted_school_ids", "declinedschoolids":"declined_school_ids", "switchboardtype":"switchboard_type", "useswitchboard":"use_switchboard", "switchboarded":"switchboarded", "updatedat":"updated_at", "expansionlevel":"expansion_level", 
"degreelevels":"degree_levels", "levelrank":"level_rank", "requiredlevelrank":"required_level_rank", "code":"code", "edulvl":"edu_lvl", "deglvl":"deg_lvl", "slug":"slug", "targetlevelid":"target_level_id", "programscount":"programs_count", "companies":"companies", "cotype":"co_type", "schoolapi":"school_api", "contactname":"contact_name", "contactemail":"contact_email", "group":"group", "enabled":"enabled", "remarketflags":"remarket_flags", "brand":"brand", "product":"product", "trackingcode":"tracking_code", 
"usewidgetprequalifypage":"use_widget_prequalify_page", "referralsstudyareas":"referrals_study_areas", "applications":"applications", "enrollments":"enrollments", "starts":"starts", "searchresults":"search_results", "featurelevel":"feature_level", "programids":"program_ids", "selectedprogramid":"selected_program_id", "viewedat":"viewed_at", "campusidsbyprogramid":"campus_ids_by_program_id", "budgets":"budgets", "ownerid":"owner_id", "ownertype":"owner_type", "year":"year", "month":"month", "monthlycap":"monthly_cap", 
"monthlycount":"monthly_count", "dailycap":"daily_cap", "dailycount":"daily_count", "sequence":"sequence", "revenueperlead":"revenue_per_lead", "expectedquality":"expected_quality", "leeway":"leeway", "junkquality":"junk_quality", "pricingelasticity":"pricing_elasticity", "throttle":"throttle", "flowcontrol":"flow_control", "frozenat":"frozen_at", "campaigncode2":"campaign_code2", "netrpl":"net_rpl", "fulfillon":"fulfill_on", "schools":"schools", "shortname":"short_name", "deletedat":"deleted_at", 
"deletedreason":"deleted_reason", "logofilename":"logo_file_name", "logocontenttype":"logo_content_type", "logofilesize":"logo_file_size", "photofilename":"photo_file_name", "photocontenttype":"photo_content_type", "photofilesize":"photo_file_size", "campus":"campus", "online":"online", "onapi":"on_api", "client":"client", "ipedsid":"ipeds_id", "logoupdatedat":"logo_updated_at", "photoupdatedat":"photo_updated_at", "website":"website", "reportsenrolls":"reports_enrolls", "iconfilename":"icon_file_name", 
"iconcontenttype":"icon_content_type", "iconfilesize":"icon_file_size", "iconupdatedat":"icon_updated_at", "exclusive":"exclusive", "submitbeforetransfer":"submit_before_transfer", "excludeinsuperquery":"exclude_in_super_query", "masterschoolid":"master_school_id", "studyareas":"study_areas", "parentid":"parent_id", "articleid":"article_id", "imagefilename":"image_file_name", "imagecontenttype":"image_content_type", "imagefilesize":"image_file_size", "rootid":"root_id", "popularityrank":"popularity_rank", 
"sampletopics":"sample_topics", "schoolsstudyareas":"schools_study_areas", "nrtreferrals":"nrt_referrals", "converted":"converted", "targetname":"target_name", "nrtmetricid":"nrt_metric_id", "programs":"programs", "requiredlevelid":"required_level_id", "statemappingscount":"state_mappings_count", "zipmappingscount":"zip_mappings_count", "popularity":"popularity", "fieldvalues":"field_values", "fieldid":"field_id", "masterschools":"master_schools", "campuses":"campuses", "campusesdegreelevels":"campuses_degree_levels", 
"campusesprograms":"campuses_programs", "campusesstudyareas":"campuses_study_areas", "budgetlimits":"budget_limits", "cached":"cached", "programsstudyareas":"programs_study_areas", "schoolsdegreelevels":"schools_degree_levels", "costs":"costs", "attributeeid":"attributee_id", "attributeetype":"attributee_type", "recipientid":"recipient_id", "recipienttype":"recipient_type", "lsdi":"lsdi", "lsdiaddress":"lsdi_address", "lsdiaddress2":"lsdi_address2", "lsdizip":"lsdi_zip", "lsdizip4":"lsdi_zip4", "addresstypeind":"address_type_ind", 
"addressline":"address_line", "censustract":"census_tract", "censusblockgroup":"census_block_group", "censusblock":"census_block", "lsdicity":"lsdi_city", "lsdistate":"lsdi_state", "fipsstatecode":"fips_state_code", "fipscountycode":"fips_county_code", "msacode":"msa_code", "cbsacode":"cbsa_code", "lsdifname":"lsdi_fname", "lsdimi":"lsdi_mi", "lsdilname":"lsdi_lname", "lsdiprefix":"lsdi_prefix", "dobyr":"dob_yr", "dobmth":"dob_mth", "exactage":"exact_age", "esthhincome":"est_hh_income", "networth":"net_worth", 
"multilinescreditind":"multi_lines_credit_ind", "newcreditind":"new_credit_ind", "amexgoldcc":"amex_gold_cc", "amexregularcc":"amex_regular_cc", "discovergoldcc":"discover_gold_cc", "discoverregularcc":"discover_regular_cc", "retailpremiumcc":"retail_premium_cc", "retailcc":"retail_cc", "mastercardgoldcc":"mastercard_gold_cc", "mastercardregularcc":"mastercard_regular_cc", "visagoldcc":"visa_gold_cc", "visaregularcc":"visa_regular_cc", "checkingaccount":"checking_account", "gasretailcc":"gas_retail_cc", 
"travelentertnmntcc":"travel_entertnmnt_cc", "othercc":"other_cc", "premiumcc":"premium_cc", "deptstorecc":"dept_store_cc", "freqccuser":"freq_cc_user", "newccuser":"new_cc_user", "bankcardholder":"bankcard_holder", "investmentactive":"investment_active", "investmentpersonal":"investment_personal", "investmentrealestate":"investment_real_estate", "investmentstocksbonds":"investment_stocks_bonds", "internatlinvestor":"internatl_investor", "investmentpropertyowned":"investment_property_owned", "loantovalue":"loan_to_value", 
"creditrating":"credit_rating", "education":"education", "occupation":"occupation", "occupationdetailed":"occupation_detailed", "businessowner":"business_owner", "bizopseeker":"bizop_seeker", "conteduinterest":"cont_edu_interest", "africanamericanprofessional":"african_american_professional", "careerminded":"career_minded", "onlineeduinterest":"online_edu_interest", "numberofchildren":"number_of_children", "poc":"poc", "numberofadults":"number_of_adults", "generationsinhh":"generations_in_hh", "veteraninhh":"veteran_in_hh", 
"singleparentind":"single_parent_ind", "youngchildrenhhind":"young_children_hh_ind", "schoolagechildren":"school_age_children", "childrenprodclustercode":"children_prod_cluster_code", "youngadultind":"young_adult_ind", "seniorind":"senior_ind", "grandparentind":"grandparent_ind", "christianfamilyind":"christian_family_ind", "petind":"pet_ind", "catowner":"cat_owner", "dogowner":"dog_owner", "birdowner":"bird_owner", "otherpetowner":"other_pet_owner", "workingwomenhh":"working_women_hh", "sohoindicator":"soho_indicator", 
"religioushh":"religious_hh", "homeownerrenter":"homeowner_renter", "lengthresidence":"length_residence", "dwellingtype":"dwelling_type", "homemarketvalue":"homemarket_value", "homeimprovement":"home_improvement", "homeimprovementneed":"home_improvement_need", "homepurchasedate":"home_purchase_date", "homepurchaseprice":"home_purchase_price", "homesalestype":"home_sales_type", "homeyearbuilt":"home_year_built", "airconditioning":"air_conditioning", "pool":"pool", "fuel":"fuel", "sewer":"sewer", "water":"water", 
"mailorderbuyer":"mail_order_buyer", "mailorderresponder":"mail_order_responder", "catalogbuyer":"catalog_buyer", "onlinebuyer":"online_buyer", "warehouseclub":"warehouse_club", "discountshopper":"discount_shopper", "clothingbuyerwomen":"clothing_buyer_women", "clothingbuyerwomenpetite":"clothing_buyer_women_petite", "clothingbuyerwomenplus":"clothing_buyer_women_plus", "clothingbuyerwomenjunior":"clothing_buyer_women_junior", "clothingbuyermen":"clothing_buyer_men", "clothingbuyermenplus":"clothing_buyer_men_plus", 
"clothingbuyermenyoung":"clothing_buyer_men_young", "clothingbuyerchildren":"clothing_buyer_children", "healthprodbuyer":"health_prod_buyer", "cosmeticbuyer":"cosmetic_buyer", "jewelrybuyer":"jewelry_buyer", "luggagebuyer":"luggage_buyer", "toybuyer":"toy_buyer", "babyproductbuyer":"baby_product_buyer", "childrenprodbuyer":"children_prod_buyer", "magazinesub":"magazine_sub", "bookbuyer":"book_buyer", "audiobookbuyer":"audio_book_buyer", "computeraccbuyer":"computer_acc_buyer", "luxappliancebuyer":"lux_appliance_buyer", 
"consumerelectrbuyer":"consumer_electr_buyer", "antiquesbuyer":"antiques_buyer", "artbuyer":"art_buyer", "sportsmemorbuyer":"sports_memor_buyer", "houseplantsbuyer":"house_plants_buyer", "hhproductsbuyer":"hh_products_buyer", "gardeningbuyer":"gardening_buyer", "photographyequipmntbuyer":"photography_equipmnt_buyer", "furniturebuyer":"furniture_buyer", "gourmetcookingbuyer":"gourmet_cooking_buyer", "organicfoodbuyer":"organic_food_buyer", "sportinggoodsbuyer":"sporting_goods_buyer", "huntingbuyer":"hunting_buyer", 
"vitaminbuyer":"vitamin_buyer", "dietingbuyer":"dieting_buyer", "autopartbuyer":"auto_part_buyer", "financepubreader":"finance_pub_reader", "childrenmagsub":"children_mag_sub", "horseridingind":"horse_riding_ind", "readinginterest":"reading_interest", "religiousreadinginterest":"religious_reading_interest", "scifireadinginterest":"scifi_reading_interest", "magazinereader":"magazine_reader", "audiobookinterest":"audio_book_interest", "historymilitarybuff":"history_military_buff", "politicalinterest":"political_interest", 
"astronomyinterest":"astronomy_interest", "gameplayer":"game_player", "moviebuyerrenter":"movie_buyer_renter", "hometheater":"home_theater", "musicenthusiast":"music_enthusiast", "moviecollector":"movie_collector", "videogamer":"video_gamer", "computergames":"computer_games", "moviemusiccluster":"movie_music_cluster", "theaterenthusiast":"theater_enthusiast", "fineartsenthusiast":"fine_arts_enthusiast", "musicinstrumentshh":"music_instruments_hh", "collectiblesinterest":"collectibles_interest", "stampenthusiast":"stamp_enthusiast", 
"coinenthusiast":"coin_enthusiast", "artenthusiast":"art_enthusiast", "antiquesenthusiast":"antiques_enthusiast", "avidcollector":"avid_collector", "militaryenthusiast":"military_enthusiast", "collectiblecluster":"collectible_cluster", "diy":"diy", "autoworkenthusiast":"auto_work_enthusiast", "knittingsewingenthusiast":"knitting_sewing_enthusiast", "woodworkenthusiast":"woodwork_enthusiast", "photographyenthusiast":"photography_enthusiast", "aviationenthusiast":"aviation_enthusiast", "craftenthusiast":"craft_enthusiast", 
"gardeningenthusiast":"gardening_enthusiast", "wineenthusiast":"wine_enthusiast", "cookingenthusiast":"cooking_enthusiast", "cookingfoodcluster":"cooking_food_cluster", "crosswordpuzzleplayer":"crossword_puzzle_player", "casinogambler":"casino_gambler", "sweepsenthusiast":"sweeps_enthusiast", "travelinterest":"travel_interest", "domestictravel":"domestic_travel", "internatltravel":"internatl_travel", "cruiseinterest":"cruise_interest", "athomeenthusiast":"at_home_enthusiast", "handsonenthusiast":"hands_on_enthusiast", 
"activelivingenthusiast":"active_living_enthusiast", "luxurylifestyleenthusiast":"luxury_lifestyle_enthusiast", "culturalartsenthusiast":"cultural_arts_enthusiast", "hitechearlyadopter":"hi_tech_early_adopter", "healthylivingenthusiast":"healthy_living_enthusiast", "runningenthusiast":"running_enthusiast", "bicyclingenthusiast":"bicycling_enthusiast", "avidwalker":"avid_walker", "exerciseclassenthusiast":"exercise_class_enthusiast", "autoracingenthusiast":"auto_racing_enthusiast", "sportsfan":"sports_fan", 
"footballenthusiast":"football_enthusiast", "baseballenthusiast":"baseball_enthusiast", "basketballenthusiast":"basketball_enthusiast", "hockeyenthusiast":"hockey_enthusiast", "soccerenthusiast":"soccer_enthusiast", "tennisenthusiast":"tennis_enthusiast", "golfenthusiast":"golf_enthusiast", "skisnowboardenthusiast":"ski_snowboard_enthusiast", "swimmingenthusiast":"swimming_enthusiast", "motorcyclingenthusiast":"motorcycling_enthusiast", "nascarenthusiast":"nascar_enthusiast", "boatingenthusiast":"boating_enthusiast", 
"scubaenthusiast":"scuba_enthusiast", "avidfisher":"avid_fisher", "campingenthusiast":"camping_enthusiast", "avidhunter":"avid_hunter", "selfimproventhusiast":"self_improv_enthusiast", "donor":"donor", "donormailorder":"donor_mail_order", "donorvarcharitable":"donor_varcharitable", "donoranimal":"donor_animal", "donorarts":"donor_arts", "donorchildren":"donor_children", "donorwildlife":"donor_wildlife", "donorenvironmental":"donor_environmental", "donormedresearch":"donor_med_research", "donorhumanitrn":"donor_humanitrn", 
"donorpolitical":"donor_political", "donorrepublican":"donor_republican", "donordemocrat":"donor_democrat", "donorreligious":"donor_religious", "donorveterans":"donor_veterans", "donorothers":"donor_others", "donorcommunity":"donor_community", "ethniccode":"ethnic_code", "ethnicconfidence":"ethnic_confidence", "ethnicgroup":"ethnic_group", "language":"language", "religion":"religion", "hispaniccountrycode":"hispanic_country_code", "assimilationcode":"assimilation_code", "fact":"fact", "five9":"five9", 
"calls":"calls", "callid":"call_id", "timestamp":"timestamp", "sessionid":"session_id", "contacted":"contacted", "contactattempts":"contact_attempts", "liveconnect":"live_connect", "handletime":"handle_time", "talktime":"talk_time", "calltype":"call_type", "listname":"list_name", "agentlastname":"agent_last_name", "agentfirstname":"agent_first_name", "number1":"number1", "eduteacher":"edu_teacher", "eduhsgradyr":"edu_hsgradyr", "edutrackjob":"edu_track_job", "edutrackurl":"edu_track_url", "edutrackuniqueid":"edu_track_unique_id", 
"edutrackvendorid":"edu_track_vendor_id", "edutracksubid":"edu_track_sub_id", "edutrackchannelid":"edu_track_channel_id", "edugender":"edu_gender", "educitizenship":"edu_citizenship", "edustartrange":"edu_startrange", "edustartmonth":"edu_startmonth", "edubirthyear":"edu_birthyear", "edumilstatus":"edu_milstatus", "eduedulevel":"edu_edulevel", "blcincome":"blc_income", "blcscore":"blc_score", "blcqscore":"blc_qscore", "blcamt":"blc_amt", "blcltype":"blc_ltype", "blcdebtamt":"blc_debt_amt", "mrtsourceid":"mrt_sourceid", 
"mrtmaLoanType2":"mrt_ma_LoanType2", "mrtmatloan":"mrt_ma_tloan", "dnis":"dnis", "ani":"ani", "statestatistics":"state_statistics", "agentemail":"agent_email", "notreadytime":"not_ready_time", "readytime":"ready_time", "waittime":"wait_time", "ringingtime":"ringing_time", "oncalltime":"on_call_time", "manualtime":"manual_time", "onacwtime":"on_acw_time", "paidtime":"paid_time", "unpaidtime":"unpaid_time", "callcenterdailyfixedoperatingcosts":"call_center_daily_fixed_operating_costs", "startdate":"start_date", 
"enddate":"end_date", "agents":"agents", "agentgroup":"agent_group", "agentstartdate":"agent_start_date", "createtime":"create_time", "edulistname":"edu_list_name", "edutracksourceid":"edu_track_source_id", "eduavatarid":"edu_avatarid", "edutrackmarketingchannel":"edu_track_marketing_channel", "edutrackeventid":"edu_track_event_id", "edutrackavatarid":"edu_track_avatarid", "eduipaddress":"edu_ipaddress", "eduaoi1":"edu_aoi1", "eduaoi2":"edu_aoi2", "eduaoi3":"edu_aoi3", "edumodality":"edu_modality", 
"edurn":"edu_rn", "edusrcsubid":"edu_srcsubid", "blcformpn":"blc_formpn", "blcroo":"blc_roo", "blcyob":"blc_yob", "listcontacts":"listcontacts", "listcontactid":"list_contact_id", "assignmenttime":"assignmenttime", "dialattempts":"dial_attempts", "unreachabledonotdial":"unreachable_do_not_dial", "unreachablemaxattempts":"unreachable_max_attempts", "unreachable":"unreachable", "campaigntype":"campaign_type", "unreachablednc":"unreachable_dnc", "lastcalltime":"lastcalltime", "finaldisposition":"finaldisposition", 
"lastdisposition":"lastdisposition", "helios":"helios", "campaignstatistics":"campaign_statistics", "internalcampaignname":"internal_campaign_name", "date":"date", "hours":"hours", "transfers":"transfers", "dncs":"dncs", "foreignids":"foreign_ids", "campaignmapping":"campaign_mapping", "helioscampaignid":"helios_campaign_id", "callcampaignid":"call_campaign_id", "heliospayout":"helios_payout", "matches":"matches", "uniquecallid":"unique_call_id", "phonenumber":"phone_number", "apiname":"api_name", 
"schoolname":"school_name", "programname":"program_name", "matchtime":"match_time", "nomatches":"no_matches", "searchidentifier":"search_identifier", "searchdate":"search_date", "prospectfirstname":"prospect_firstname", "prospectlastname":"prospect_lastname", "prospectphone1":"prospect_phone1", "prospectstreet1":"prospect_street1", "prospectcity":"prospect_city", "prospectstate":"prospect_state", "prospectpostalcode":"prospect_postal_code", "label":"label", "expr1":"expr1", "prospectdateofbirth":"prospect_date_of_birth", 
"prospectageyears":"prospect_age_years", "prospecthighschoolgradyear":"prospect_highschool_grad_year", "expr2":"expr2", "prospectcollegecreditsearned":"prospect_college_credits_earned", "expr3":"expr3", "prospecttimeframemonths":"prospect_timeframe_months", "prospecttrafficsourcecode":"prospect_traffic_source_code", "prospecttrafficsourceurl":"prospect_traffic_source_url", "searchoriginationccagent":"search_origination_cc_agent", "searchoriginationccbrand":"search_origination_cc_brand", "searchhaserrors":"search_has_errors", 
"prospectemail":"prospect_email", "searchoriginationcccallid":"search_origination_cc_callid", "searchoriginationccsessionid":"search_origination_cc_sessionid", "prospectaois":"prospect_aois", "searchlogtext":"search_logtext", "revenuerates":"revenue_rates", "payout":"payout", "scrubrates":"scrubrates", "scrubrate":"scrub_rate", "submissions":"submissions", "submissiondate":"submission_date", "submissionstatus":"submission_status", "submissionerrors":"submission_errors", "searchresultistransfer":"search_result_is_transfer", 
"searchresultislead":"search_result_is_lead", "searchresultcollegename":"search_result_college_name", "searchresultisonline":"search_result_is_online", "searchresultprogramname":"search_result_program_name", "searchphone1":"search_phone_1", "searchemail":"search_email", "searchagentid":"search_agent_id", "resultrevenue":"result_revenue", "callinglist":"calling_list", "five9callid":"five9_call_id", "verticalid":"vertical_id", "divisionid":"division_id", "access":"access", "nameprivate":"name_private", 
"deliverymethod":"delivery_method", "pingtype":"ping_type", "xfertype":"xfer_type", "xferphonenumber":"xfer_phone_number", "callstatuscallback":"call_status_callback", "callstatuscallbackmethod":"call_status_callback_method", "callstatuscallbackurl":"call_status_callback_url", "callstatuscallbackevents":"call_status_callback_events", "callconvertedcallback":"call_converted_callback", "callconvertedcallbackmethod":"call_converted_callback_method", "callconvertedcallbackurl":"call_converted_callback_url", 
"callconvertedcallbackdelay":"call_converted_callback_delay", "callrecord":"call_record", "dayparting":"dayparting", "dedupe":"dedupe", "dedupestatus":"dedupe_status", "dedupeinterval":"dedupe_interval", "dedupeunit":"dedupe_unit", "dedupefields":"dedupe_fields", "dedupeversion":"dedupe_version", "redirect":"redirect", "descriptionprivate":"description_private", "phonenumbercountry":"phone_number_country", "apisetpriceenabled":"api_set_price_enabled", "user":"user", "referrerid":"referrer_id", "roleid":"role_id", 
"username":"username", "password":"password", "balance":"balance", "balanceoverdrawing":"balance_overdrawing", "loginipaddress":"login_ip_address", "registeripaddress":"register_ip_address", "remembertoken":"remember_token", "lead":"lead", "advertiserid":"advertiser_id", "publisherid":"publisher_id", "publishersub1id":"publisher_sub1_id", "publishersub2id":"publisher_sub2_id", "publishersub3id":"publisher_sub3_id", "publishersub4id":"publisher_sub4_id", "publishersub5id":"publisher_sub5_id", "publishersub6id":"publisher_sub6_id", 
"publishersub7id":"publisher_sub7_id", "publishersub8id":"publisher_sub8_id", "utmcampaignid":"utm_campaign_id", "utmcontentid":"utm_content_id", "utmmediumid":"utm_medium_id", "utmsourceid":"utm_source_id", "utmtermid":"utm_term_id", "accepted":"accepted", "acceptedpub":"accepted_pub", "rejectedreason":"rejected_reason", "rejectedreasonpub":"rejected_reason_pub", "reasondata":"reason_data", "payin":"payin", "data":"data", "soldposition":"sold_position", "postedat":"posted_at", "servedin":"served_in", 
"call":"call", "callsid":"call_sid", "phonenumberid":"phone_number_id", "from":"from", "fromtype":"from_type", "to":"to", "totype":"to_type", "callstatus":"call_status", "fromcity":"from_city", "fromstate":"from_state", "fromzip":"from_zip", "fromcountry":"from_country", "tocity":"to_city", "tostate":"to_state", "tozip":"to_zip", "tocountry":"to_country", "callduration":"call_duration", "recordingsid":"recording_sid", "recordingurl":"recording_url", "transaction":"transaction", "paymentid":"payment_id", 
"transactionid":"transaction_id", "userid":"user_id", "reasondeclined":"reason_declined", "amount":"amount", "note":"note", "category":"category", "campaigncategory":"campaign_category", "publishersub":"publisher_sub", "trackingparameter":"tracking_parameter", "campaigndeliveryid":"campaign_delivery_id", "verticaldeliveryid":"vertical_delivery_id", "erreqres":"erreqres", "filtered":"filtered", "filteredby":"filtered_by", "reqat":"req_at", "reqtime":"req_time", "resvcode":"resvcode", "campaigndelivery":"campaign_delivery", 
"deliveryid":"delivery_id", "priority":"priority", "enabledexpr":"enabled_expr", "loanadvisorflat":"loanadvisor_flat", "passed":"passed", "failed":"failed", "global":"global", "offers":"offers", "lender":"lender", "offerid":"offer_id", "apps":"apps", "apprate":"app_rate", "funded":"funded", "fundedamount":"funded_amount", "utmsubid1":"utm_subid_1", "utmsubid2":"utm_subid_2", "utmsubid3":"utm_subid_3", "lenderfailreason":"lender_fail_reason", "brrcrm":"brr_crm", "crmid":"crm_id", "besttimetocontact":"best_time_to_contact", 
"spousename":"spouse_name", "spouseoccupationlength":"spouse_occupation_length", "spouseoccupationname":"spouse_occupation_name", "autoexpenses":"auto_expenses", "bankruptcy713":"bankruptcy7_13", "bankruptcydischarged":"bankruptcy_discharged", "everfiledbk":"ever_filed_bk", "grossmonthlyincome":"gross_monthly_income", "minmonthlypayments":"min_monthly_payments", "monthlyincome":"monthly_income", "mortgagerent":"mortgage_rent", "notes":"notes", "othermonthlyexpenses":"other_monthly_expenses", "spousegrossmonthlyincome":"spouse_gross_monthly_income", 
"ssnhers":"ssn_hers", "ssnhis":"ssn_his", "estvalue":"est_value", "lastappraiseddate":"last_appraised_date", "lastappraisedvalue":"last_appraised_value", "numberofcreditcards":"number_of_credit_cards", "occupationlength":"occupation_length", "occupationname":"occupation_name", "realisticmonthlycreditcardpayments":"realistic_monthly_credit_card_payments", "totalcreditcarddebt":"total_credit_card_debt", "utilities":"utilities", "lastrefinanced":"last_refinanced", "cashout":"cash_out", "cashoutvalue":"cash_out_value", 
"originalpurchaseprice":"original_purchase_price", "originalpurchasedate":"original_purchase_date", "datecreated":"date_created", "dateupdated":"date_updated", "deleted":"deleted", "viewable":"viewable", "attachedto":"attached_to", "oldleadid":"old_lead_id", "weight":"weight", "tobacco":"tobacco", "tobacconotes":"tobacco_notes", "married":"married", "kids":"kids", "currentlyinsured":"currently_insured", "coverageamount":"coverage_amount", "condition":"condition", "lotrasnferedto":"lo_trasnfered_to", 
"nonequalified":"nonequalified", "fico":"fico", "credithistory":"credit_history", "currentonpayment":"current_on_payment", "oldcollectionorcurrent":"old_collection_or_current", "latepaymentlastyear":"late_payment_last_year", "propertyinfo":"property_info", "residenselength":"residense_length", "repairgoal":"repair_goal", "repairdate":"repair_date", "inboundcall":"inbound_call", "loanterm":"loan_term", "firsttimebuyer":"first_time_buyer", "timeframeold":"time_frame_old", "speaktorealtor":"speak_to_realtor", 
"advrealtysent":"advrealty_sent", "preapproved":"preapproved", "primaryresidence":"primary_residence", "singlefamilyresidence":"singlefamily_residence", "desiredloantype":"desired_loan_type", "residencetype":"residence_type", "hadreversemortgage":"had_reverse_mortgage", "militaryaffiliate":"militaryaffiliate", "shortsale":"shortsale", "combinedloanamountrefi":"combined_loanamount_refi", "jornayalead":"jornaya_lead", "timeframe":"time_frame", "loanmod":"loanmod", "bedroomcount":"bedroom_count", "bathroomcount":"bathroom_count", 
"squarefootage":"square_footage", "havepool":"have_pool", "securityphrase":"security_phrase", "bankruptcydischarged2years":"bankruptcy_discharged_2_years", "helloc":"helloc", "orders":"orders", "orderpk":"orderpk", "orderid":"order_id", "ordername":"ordername", "ordertotalcount":"ordertotalcount", "ordertodayscount":"ordertodayscount", "attacheduser":"attacheduser", "active":"active", "ordertype":"ordertype", "emailstosend":"emailstosend", "lastleadrecieved":"lastleadrecieved", "crmname":"crm_name", 
"crmurl":"crm_url", "crmpayload":"crm_payload", "invoiceid":"invoice_id", "salesguy":"sales_guy", "oldcampaignid":"old_campaign_id", "nextday":"next_day", "transferphone":"transfer_phone", "ordercolor":"order_color", "vip":"vip", "delay":"delay", "displayname":"display_name", "returnpolicy":"return_policy", "returnpolicydate":"return_policy_date", "priceperlead":"price_per_lead", "loemaillist":"lo_email_list", "crmuser":"crm_user", "crmpw":"crm_pw", "customphones":"custom_phones", "ordertier":"order_tier", 
"loantype":"loan_type", "phonestaterel":"phone_state_rel", "maxltv":"max_ltv", "hidephone":"hide_phone", "mortgagerate":"mortgage_rate", "musthavecashout":"must_have_cashout", "mustneverhavecashout":"must_never_have_cashout", "tmcommission":"tm_commission", "jornayamust":"jornayamust", "dupecheckcontactid":"dupe_check_contact_id", "ordersleadsrel":"orders_leads_rel", "olrid":"olr_id", "datereturned":"date_returned", "returncomments":"return_comments", "returnstatus":"return_status", "returnnotes":"return_notes", 
"sentby":"sent_by", "transfertype":"transfer_type", "sent":"sent", "response":"response", "tmattached":"tm_attached", "returnapprovedby":"return_approved_by", "totalordersavailable":"total_orders_available", "stratustime":"stratustime", "empidentifier":"emp_identifier", "employeeclassification":"employee_classification", "employeetype":"employee_type", "manager":"manager", "managereffdate":"manager_eff_date", "managerid":"manager_id", "statuseffdate":"status_eff_date", "timezoneisdst":"time_zone_is_dst", 
"timezoneutcoffset":"time_zone_utc_offset", "payrate":"pay_rate", "payrateeffdate":"pay_rate_eff_date", "salarytype":"salary_type", "salarytypeeffdate":"salary_type_eff_date", "punchtimes":"punch_times", "paytypeid":"pay_type_id", "paytypename":"pay_type_name", "paytypecode":"pay_type_code", "applytodate":"apply_to_date", "intype":"in_type", "outtime":"out_time", "outtimeactual":"out_time_actual", "outtimeslicepreid":"out_time_slice_pre_id", "outtype":"out_type", "regularminutes":"regular_minutes", 
"unpaidminutes":"unpaid_minutes", "subdivisionid":"subdivision_id", "divisions":"divisions", "defaulteffectivedate":"default_effective_date", "modifiedemployeeid":"modified_employee_id", "modifiedon":"modified_on", "payadjustments":"pay_adjustments", "empapproved":"emp_approved", "mgrapproved":"mgr_approved", "payadjustmentdate":"pay_adjustment_date", "payadjustmentid":"pay_adjustment_id", "payperunit":"pay_per_unit", "timeslicepreid":"time_slice_pre_id", "unit":"unit", "payadjustmentsdict":"pay_adjustments_dict", 
"payadjustid":"pay_adjust_id", "startdatetime":"start_datetime", "enddatetime":"end_datetime", "teledrip":"teledrip", "longtransfers":"long_transfers", "outbound":"outbound", "inbound":"inbound", "smssent":"sms_sent", "smsreceived":"sms_received", "transferspercent":"transfers_percent", "longpercent":"long_percent"}, "patterns":{"companyemail":"/[^A-Za-z0-9]/", "email":"/[^A-Za-z0-9]/", "email_consent":"/[^A-Za-z0-9]/", "email_job_alert":"/[^A-Za-z0-9]/", "email_reason":"/[^A-Za-z0-9]/", "email_score":"/[^A-Za-z0-9]/", 
"email_valid":"/[^A-Za-z0-9]/", "lender_email":"/[^A-Za-z0-9]/"}, "privates":{"credit_score":true, "dob":true, "email":true, "medical_condition":true, "mobile":true, "ssn_last_4":true}};
function queryDmap(question, answer) {
  var mappedQuestionKey = getDmapMapping(question);
  if (!mappedQuestionKey) {
    return [question, answer];
  }
  if (__dmapValues["privates"][mappedQuestionKey]) {
    return [mappedQuestionKey, "*********"];
  }
  if (mappedPattern = __dmapValues["patterns"][mappedQuestionKey]) {
    return [mappedQuestionKey, applyDmapPattern(answer, __dmapValues["patterns"][mappedQuestionKey])];
  }
  return [mappedQuestionKey, answer];
}
function modifyQueryInput(queryInput) {
  return queryInput.replace(/[^A-Za-z0-9]/, "");
}
function getDmapMapping(keyString) {
  keyString = modifyQueryInput(keyString);
  if (__dmapValues["mappings"].hasOwnProperty(keyString)) {
    return __dmapValues["mappings"][keyString];
  }
  return false;
}
function applyDmapPattern(valueString, pattermString) {
  return valueString.replace(new RegExp(pattermString), "");
}
;
